white space = "\n" | "\t | " "
line comment = "#", ?any character? - "\n" 
junk = {white space | line comment}

letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" 

octal = "1" | "2" | "3" | "4" | "5" | "6" | "7"  "0"
decimal = octal | "8" | "9"  
hex = letter | decimal
number = decimal, {decimal}

float = (number, ".", {decimal}) | ({decimal}, ".", number)

infix start = "$" | "%"| "&" | "*" | "+" | "-" | "." | "/" | ":" | "<" | "=" | ">" | "@" | "^" | "|" 

infix symbol = infix_start | "!' | "?" | "~"

infix = infix start, {infix symbol}
infix as symbol = "(", junk, infix start, junk, ")"

ident part = letter | "_"
ident word = ident part, {ident part | decimal}
ident = infix as symbol | ident word

type = (("(", junk, type, junk, ")") | ident word), [junk, "->", junk, type]
type annotation = ":", junk, type

fun params = {junk, ident, junk, [type annotation]}
fun = "fun", params, junk, "->" expr

let = ("let", junk, ident), [fun params], junk, "=", junk, expr, [junk, "in", junk, expr]

if = "if", junk, expr, junk, "then", junk, expr, junk, "else", junk, expr

escaped = "\\", ("\\" | "\"" | "n" | "r" | "f" | "a" | "b" | "t" | "v" | "0" | (octal, octal, octal) | ("x", hex, hex) |  ("u", hex, hex, hex, hex) | ("U", hex, hex, hex, hex, hex, hex, hex, hex) )

string part = escaped | ?any character? - "\""
string = {string part}

infix application = expr, junk, infix, junk, expr
application = expr, junk, expr, {junk, expr}

expr = ("(", junk, expr, junk, ")") | number | float | ident | fun | let | infix application | application  | ("\"", string, "\"") | if

program = {string | ("\"", junk, expr, junk, "\"")}
